EmprestimoLivro/Models/EmprestimosModel.cs
using System.ComponentModel.DataAnnotations;

namespace EmprestimoLivro.Models
{
    public class EmprestimosModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Informe o nome do recebedor")]
        public string Recebedor { get; set; }

        [Required(ErrorMessage = "Informe o nome do forncedor")]
        public string Fornecedor { get; set; }

        [Required(ErrorMessage = "Informe o nome do livro")]
        public string LivroEmprestado { get; set; }
        public DateTime dataUltimaAtualizacao { get; set; } = DateTime.Now;
    }
}

EmprestimoLivro/Models/ErrorViewModel.cs
namespace EmprestimoLivro.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmprestimoLivro/Controllers/EmprestimoController.cs
using EmprestimoLivro.Data;
using EmprestimoLivro.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmprestimoLivro.Controllers
{
    public class EmprestimoController : Controller
    {
        readonly private AppDbContext _db;

        public EmprestimoController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<EmprestimosModel> emprestimos = _db.Emprestimos;
            return View(emprestimos);
        }

        [HttpGet]
        public IActionResult Excluir(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            EmprestimosModel emprestimo = _db.Emprestimos.FirstOrDefault(x => x.Id == id);

            if (emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        [HttpPost]
        public IActionResult Excluir(EmprestimosModel emprestimo)
        {
            if (emprestimo == null)
            {
                return NotFound();
            }

            _db.Emprestimos.Remove(emprestimo);
            _db.SaveChanges();

            TempData["MensagemSucesso"] = "Exclusão realizado com sucesso!";

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            EmprestimosModel emprestimo = _db.Emprestimos.FirstOrDefault(x => x.Id == id);

            if (emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        [HttpPost]
        public IActionResult Editar(EmprestimosModel emprestimo)
        {
            if (ModelState.IsValid)
            {
                _db.Emprestimos.Update(emprestimo);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Edição realizado com sucesso!";

                return RedirectToAction("Index");
            }
            TempData["MensagemErro"] = "Algum erro ocorreu ao realizar a edição";

            return View(emprestimo);
        }

        [HttpGet]
        public IActionResult Cadastrar() 
        {
            return View();        
        }

        [HttpPost]
        public IActionResult Cadastrar(EmprestimosModel emprestimos)
        {
            if (ModelState.IsValid)
            {
                _db.Emprestimos.Add(emprestimos);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Cadastro realizado com sucesso!";

                return RedirectToAction("Index");
            }
            TempData["MensagemErro"] = "Algum erro ocorreu ao realizar o cadasatro";

            return View();
        }
    }
}

EmprestimoLivro/Controllers/HomeController.cs
using EmprestimoLivro.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmprestimoLivro.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmprestimoLivro/Views/Emprestimo/Cadastrar.cshtml
@model EmprestimosModel;

@{
    ViewData["Title"] = "Cadastrar Empréstimo";
}

<div class="container bg-light p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-dark">Cadastro de Empréstimos</h1>
    </div>

    <form method="post" asp-controller="Emprestimo" asp-action="Cadastrar">
        
        <div class="mb-3">
            <label for="Recebedor" class="form-label">Recebedor</label>
            <input type="text" class="form-control" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o livro?">
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>

        <div class="mb-3">
            <label for="Fornecedor" class="form-label">Fornecedor</label>
            <input type="text" class="form-control" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando?">
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label">Livro</label>
            <input type="text" class="form-control" asp-for="LivroEmprestado" id="Livro" placeholder="Qual o livro?">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Cadastrar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>

    </form>
</div>

EmprestimoLivro/Views/Emprestimo/Editar.cshtml
@model EmprestimosModel;

@{
    ViewData["Title"] = "Editar Empréstimo";
}

<div class="container bg-light p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-dark">Edição de Empréstimos</h1>
    </div>

    <form method="post" asp-controller="Emprestimo" asp-action="Editar">
        <input type="hidden" asp-for="Id" />

        <div class="mb-3">
            <label for="Recebedor" class="form-label">Recebedor</label>
            <input type="text" class="form-control" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o livro?">
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>

        <div class="mb-3">
            <label for="Fornecedor" class="form-label">Fornecedor</label>
            <input type="text" class="form-control" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando?">
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label">Livro</label>
            <input type="text" class="form-control" asp-for="LivroEmprestado" id="Livro" placeholder="Qual o livro?">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Editar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>

    </form>
</div>

EmprestimoLivro/Views/Emprestimo/Excluir.cshtml
@model EmprestimosModel;

@{
    ViewData["Title"] = "Excluir Empréstimo";
}

<div class="container bg-light p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-dark">Excluir Empréstimos</h1>
    </div>

    <form method="post" asp-controller="Emprestimo" asp-action="Excluir">
        <input type="hidden" asp-for="Id" />

        <h2>Deseja realmente excluiro registro abaixo?</h2>

        <div class="mb-3">
            <label for="Recebedor" class="form-label">Recebedor</label>
            <input type="text" class="form-control" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o livro?" disabled>
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>

        <div class="mb-3">
            <label for="Fornecedor" class="form-label">Fornecedor</label>
            <input type="text" class="form-control" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando?" disabled>
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label">Livro</label>
            <input type="text" class="form-control" asp-for="LivroEmprestado" id="Livro" placeholder="Qual o livro?" disabled>
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>

    </form>
</div>

EmprestimoLivro/Views/Emprestimo/Index.cshtml
@model IEnumerable<EmprestimosModel>

<div class="container">

    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Empréstimos</h1>
        <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Cadastrar"><i class="bi bi-file-earmark-plus mx-2"></i>Cadastrar Novo Empréstimo</a>
    </div>

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success text-light" role="alert">
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger text-light" role="alert">
            @TempData["MensagemErro"]
        </div>
    }

    <table class="table table-hover table-light mt-5" id="Emprestimos"> 
        <thead>
            <tr>
                <th scope="col">Recebedor</th>
                <th scope="col">Fornecedor</th>
                <th scope="col">Livro</th>
                <th scope="col">Última Atualização</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                @foreach (var emprestimo in Model)
                {
                    <tr>
                        <th scope="row">@emprestimo.Recebedor</th>
                        <td>@emprestimo.Fornecedor</td>
                        <td>@emprestimo.LivroEmprestado</td>
                        <td>@emprestimo.dataUltimaAtualizacao</td>
                        <td>
                            <a class="btn btn-warning mx-2" asp-controller="Emprestimo" asp-route-id="@emprestimo.Id" asp-action="Editar"><i class="bi bi-pencil-square mx-2"></i>Editar</a>
                            <a class="btn btn-danger mx-2" asp-controller="Emprestimo" asp-route-id="@emprestimo.Id" asp-action="Excluir"><i class="bi bi-trash3 mx-2"></i>Excluir</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

EmprestimoLivro/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Empréstimos Online</h1>
    <p>Quem ama livros tem sempre uma biblioteca dentro de si.</p>

    <div>
        <img src="~/images/LivroIndex.png" />
    </div>
</div>

EmprestimoLivro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmprestimoLivro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/lumen.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmprestimoLivro.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">EmprestimosLivros</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house mx-2"></i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Emprestimo" asp-action="Index"><i class="bi bi-journals mx-2"></i>Empréstimos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container text-light d-flex justify-content-between">
            <div class="align-items-left">
                &copy; 2023 - EmprestimoLivro
            </div>
            <div class="align-items-end">
                <a href="#">
                    <i class="bi bi-facebook mx-2 text-light"></i></a>
                <a href="#"><i class="bi bi-instagram mx-2 text-light"></i></a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>